# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs:
  changelog:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install -g semantic-release
      - run: npx semantic-release@17

  build:
    docker:
      - image: circleci/ruby:2.3.7-stretch-node
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

workflows:
  version: 1
  build_and_changelog:
    jobs:
      - build:
          requires:
            - build
      - changes:
          requires:
            - changelog
